# Environment-specific configuration for Development
spring:
  application:
    name: rbm
  
  # Development Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      leak-detection-threshold: 60000

  # JPA Configuration for Development
  jpa:
    hibernate:
      ddl-auto: create-drop  # Recreate schema on startup (dev only)
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Development-specific logging
logging:
  level:
    com.tradebot.rbm: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

# Development server configuration
server:
  port: 8080
  servlet:
    context-path: /tradebot-api

# Development-specific settings
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all endpoints in development
